# Default values for molgenis.

replicaCount: 1

service:
  type: ClusterIP
  port: 9300

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 0
  path: /
  tls: []

master:
  image:
    repository: docker.elastic.co/elasticsearch/elasticsearch
    tag: 5.6.14
    pullPolicy: IfNotPresent
  clusterName: molgenis
  javaOpts: "-Xms1g -Xmx1g"
  resources:
    limits:
      cpu: 1
      memory: 3Gi
    requests:
      cpu: 100m
      memory: 1500Mi
  persistence:
    size: 10Gi
    claim: pvc-elasticsearch

persistence:
  enabled: false
  retain: false

nodeSelector: {
  deployPod: "true"
}

tolerations: []

affinity: {}
