apiVersion: v1
appVersion: "1.0"
description: "BioCommons Universal Transcript Archive: comprehensive genome-transcript alignments; multiple transcript sources, versions, and alignment methods"
name: molgenis-uta
version: 0.1.2
maintainers:
- name: fdlk
sources:
- https://github.com/molgenis/molgenis-ops-helm.git
