apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "molgenis.fullname" . }}
  labels:
    app: {{ template "molgenis.name" . }}
    chart: {{ template "molgenis.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "molgenis.name" . }}
      release: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ template "molgenis.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: molgenis
          image: {{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: molgenis.home
              value: /home/molgenis
            - name: opencpu.uri.host
              value: {{ .Values.opencpu }}
            - name: elasticsearch.transport.addresses
              value: {{ include "call-nested" (list . "molgenis-elasticsearch" "molgenis-elasticsearch.fullname") }}:9300
            - name: elasticsearch.cluster.name
              value: {{ index .Values "molgenis-elasticsearch" "clusterName" }}
            - name: db_uri
              value: jdbc:postgresql://{{ include "call-nested" (list . "postgresql" "postgresql.fullname") }}/{{ $.Values.postgresql.postgresqlDatabase }}
            - name: db_user
              value: {{ .Values.postgresql.postgresqlUsername }}
            - name: db_password
              valueFrom:
                secretKeyRef:
                  name: {{ include "call-nested" (list . "postgresql" "postgresql.fullname") }}
                  key: postgresql-password
            - name: admin.password
              valueFrom:
                secretKeyRef:
                  name: {{ template "molgenis.fullname" $ }}
                  key: adminpassword
              value: {{ .adminPassword | quote }}
            - name: python_script_executable
              value: {{ .Values.python.executable }}
            {{- if .sentry }}
            - name: SENTRY_SERVERNAME
              value: {{ template "molgenis.hostname" $ }}
            - name: SENTRY_RELEASE
              value: {{ .Values.image.name }}@{{ .Values.image.tag }}
            - name: SENTRY_ENVIRONMENT
              value: {{ .Values.environment }}
            {{- range $key, $value := default dict .sentry }}
            - name: SENTRY_{{ $key | snakecase | upper }}
              value: {{ $value }}
            {{- end }}
            {{- end }}
            {{- with $.Values.minio }}
            - name: minio_bucket_name
              value: {{ .defaultBucket.name }}
            - name: minio_region
              value: {{ .minioConfig.region }}
            - name: minio_endpoint
              value: http://{{ include "call-nested" (list $ "minio" "minio.fullname") }}:{{ .service.port }}
            {{- end}}
            - name: minio_access_key
              valueFrom:
                secretKeyRef:
                  name: {{ include "call-nested" (list $ "minio" "minio.fullname") }}
                  key: accesskey
            - name: minio_secret_key
              valueFrom:
                secretKeyRef:
                  name: {{ include "call-nested" (list $ "minio" "minio.fullname") }}
                  key: secretkey
            - name: CATALINA_OPTS
              value: {{ .Values.catalinaOpts }}
          ports:
            - containerPort: 8080
          volumeMounts:
          - name: pv-molgenis
            mountPath: /home/molgenis
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 5
            failureThreshold: 50
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /api/v2/version
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 30
            failureThreshold: 3
            successThreshold: 1
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
        - name: pv-molgenis
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "molgenis.fullname" .) }}
        {{- else }}
          emptyDir: {}
        {{- end -}}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}