apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "molgenis.fullname" . }}
  labels:
    app: {{ template "molgenis.name" . }}
    chart: {{ template "molgenis.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "molgenis.name" . }}
      release: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ template "molgenis.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: molgenis
        {{- with .Values.molgenis }}
          image: {{ .image.repository }}/{{ .image.name }}:{{ .image.tag }}
          imagePullPolicy: {{ .image.pullPolicy }}
          env:
            - name: molgenis.home
              value: /home/molgenis
            - name: opencpu.uri.host
              value: {{ .services.opencpu.host }}
            - name: elasticsearch.transport.addresses
              value: {{ $.Release.Name }}-molgenis-elasticsearch:9300
            - name: elasticsearch.cluster.name
              value: {{ index $.Values "molgenis-elasticsearch" "master" "clusterName" }}
            - name: db_uri
              value: jdbc:postgresql://{{ $.Release.Name -}}-postgresql/{{ $.Values.postgresql.postgresDatabase }}
            - name: db_user
              value: {{ $.Values.postgresql.postgresqlUsername }}
            - name: db_password
              value: "{{ $.Values.postgresql.postgresqlPassword }}"
            - name: admin.password
              value: "{{ .admin.password }}"
            - name: admin.email
              value: "{{ .admin.email }}"
            - name: anonymous.email
              value: "{{ .anonymous.email }}"
            - name: python_script_executable
              value: {{ .python.executable }}
            - name: mail.host
              value: "{{ .mail.host }}"
            - name: mail.username
              value: "{{ .mail.username }}"
            - name: mail.password
              value: "{{ .mail.password }}"
            - name: mail.port
              value: 587
            - name: mail.protocol
              value: smtp
            {{- if .sentry }}
            - name: SENTRY_SERVERNAME
              value: {{ template "molgenis.hostname" $ }}
            - name: SENTRY_RELEASE
              value: {{ .image.name }}@{{ .image.tag }}
            - name: SENTRY_ENVIRONMENT
              value: {{ .environment }}
            {{- range $key, $value := default dict .sentry }}
            - name: SENTRY_{{ $key | snakecase | upper }}
              value: {{ $value }}
            {{- end }}
            {{- end}}
            - name: CATALINA_OPTS
              value: {{ template "molgenis.javaOpts" $ }}
          ports:
            - containerPort: 8080
          {{- if $.Values.persistence.enabled }}
          volumeMounts:
          - name: pv-molgenis
            mountPath: /home/molgenis
          {{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 5
            failureThreshold: 25
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /api/v2/version
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 30
            failureThreshold: 3
            successThreshold: 1
          resources:
            {{ template "molgenis.resources" $ }}
        {{- end }}

{{- if .Values.persistence.enabled }}
      volumes:
        - name: pv-molgenis
          persistentVolumeClaim:
            claimName: {{ .Values.molgenis.persistence.claim }}
{{- end }}

    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
