{{- if .Values.ingress.enabled -}}
{{- $fullName := include "molgenis.fullname" . -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ $.Release.Name }}-ingress"
  labels:
    app: {{ template "molgenis.name" . }}
    chart: {{ template "molgenis.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
{{- if .Values.ingress.firewall.enabled }}
  {{- if eq .Values.ingress.firewall.kind "umcg" }}
    ingress.kubernetes.io/whitelist-source-range: {{ .Values.ingress.firewall.umcg.rules }}
  {{- else if eq .Values.ingress.firewall.kind "cluster" }}
    ingress.kubernetes.io/whitelist-source-range: {{ .Values.ingress.firewall.cluster.rules }}
  {{- end }}
{{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
    {{- if eq $.Values.molgenis.environment "development" }}
    - host: {{ .Release.Name }}.dev.molgenis.org
    {{- else if eq $.Values.molgenis.environment "test" }}
    - host: {{ .Release.Name }}.test.molgenis.org
    {{- else if eq $.Values.molgenis.environment "acceptance" }}
    - host: {{ .Release.Name }}.accept.molgenis.org
    {{- else }}
    - host: {{ .Release.Name }}.molgenis.org
    {{- end }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $.Values.service.port }}
{{- end }}
