elasticsearch:
  image: "docker.elastic.co/elasticsearch/elasticsearch-oss"
  # Enabling this will publically expose your Elasticsearch instance.
  # Only enable this if you have security enabled on your cluster
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/whitelist-source-range: 195.169.22.0/23,10.42.0.0/16
      # kubernetes.io/tls-acme: "true"
    paths: /
    hosts: 
      - logging.edge.molgenis.org
  extraEnvs:
    - name: ELASTIC_PASSWORD
      valueFrom:
        secretKeyRef:
          name: "elastic-credentials"
          key: logging.password
    - name: ELASTIC_USERNAME
      valueFrom:
        secretKeyRef:
          name: "elastic-credentials"
          key: logging.username

kibana:
  elasticsearchHosts: "https://logging.edge.molgenis.org"
  image: "docker.elastic.co/kibana/kibana-oss"
  ingress:
    enabled: true
    annotations: {}
    path: /
    hosts:
      - kibana.edge.molgenis.org
  extraEnvs:
    - name: 'ELASTICSEARCH_USERNAME'
      valueFrom:
        secretKeyRef:
          name: "elastic-credentials"
          key: logging.username
    - name: 'ELASTICSEARCH_PASSWORD'
      valueFrom:
        secretKeyRef:
          name: "elastic-credentials"
          key: logging.password
  elastic:
    username: xxxx
    password: xxxx
