elasticsearch:
  cluster.xpackEnable: true
  image: "docker.elastic.co/elasticsearch/elasticsearch-oss"
  # Enabling this will publically expose your Elasticsearch instance.
  # Only enable this if you have security enabled on your cluster
  esConfig:
    elasticsearch.yml: |
      xpack.license.self_generated.type: trial
      xpack.security.enabled: true
      #xpack.security.authProviders: [basic]
      #xpack.security.authc.realms.basic:
      #  order: 0
  ingress:
    enabled: true
    annotations:
      ingress.kubernetes.io/whitelist-source-range: 195.169.22.0/23
      kubernetes.io/ingress.class: "nginx"
    paths: /
    hosts:
      - logging.edge.molgenis.org
  extraEnvs:
    - name: ELASTIC_PASSWORD
      valueFrom:
        secretKeyRef:
          name: "elastic-credentials"
          key: logging.password
    - name: ELASTIC_USERNAME
      valueFrom:
        secretKeyRef:
          name: "elastic-credentials"
          key: logging.username
  authentication:
    username: xxxx
    password: xxxx
    
kibana:
  cluster.xpackEnable: true
  image: "docker.elastic.co/kibana/kibana-oss"
  ingress:
    enabled: true
    annotations: 
      nginx.ingress.kubernetes.io/auth-type: basic
      nginx.ingress.kubernetes.io/auth-secret: kibana-credentials
      nginx.ingress.kubernetes.io/auth-realm: "Authentication Required - kibana"
    path: /
    hosts:
      - kibana.edge.molgenis.org
  extraEnvs:
    - name: 'ELASTICSEARCH_USERNAME'
      valueFrom:
        secretKeyRef:
          name: "elastic-credentials"
          key: logging.username
    - name: 'ELASTICSEARCH_PASSWORD'
      valueFrom:
        secretKeyRef:
          name: "elastic-credentials"
          key: logging.password
  authentication:
    username: xxxx
    password: xxxx
  kibanaConfig:
    kibana.yml: |
      elasticsearch.username: {{ ELASTIC_USERNAME }}
      elasticsearch.password: {{ ELASTIC_PASSWORD }}
#      xpack.security.encryptionKey: "qwertyuiASDFGHJK123456781qAZxsW@"
#      xpack.security.sessionTimeout: 600000
#      xpack.security.authc.providers: [oidc]
#      xpack.security.authc.realms.oidc1:
#        order: 1
#
#      searchguard.openid.connect_url: https://github.com/login/oauth/authorize
#      searchguard.openid.client_id: xxxx
#      searchguard.openid.client_secret: xxxx
#      searchguard.openid.scopes: user:email,read:org
#      searchguard.openid.base_redirect_url: https://kibana.edge.molgenis.org/auth/openid/login
#      searchguard.openid.header: "Authorization"
