elasticsearch:
  clusterName: "molgenis-logging"
  image: "docker.elastic.co/elasticsearch/elasticsearch-oss"
  esJavaOpts: "-Xmx2g -Xms2g"
  # Enabling this will publically expose your Elasticsearch instance.
  # Only enable this if you have security enabled on your cluster
  ingress:
    enabled: true
    hosts:
      - logging.edge.molgenis.org
    annotations:
      ingress.kubernetes.io/whitelist-source-range: 195.169.22.0/23
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    spec:
      rules:
        - host: "logging.edge.molgenis.org"
#          http:
#            - path: /
#              backend:
#                serviceName: "molgenis-logging-master"
#                servicePort: 9200
kibana:
  clusterName: "molgenis-logging"
  elasticsearchURL: "logging.edge.molgenis.org"
  image: "docker.elastic.co/kibana/kibana-oss"
  ingress:
    enabled: true
    annotations: {}
#    path: /
    hosts:
      - molgenis-logging.edge.molgenis.org
    spec:
      rules:
        - host: "molgenis-logging.edge.molgenis.org"
#          http:
#            - paths: /
#              backend:
#                serviceName: "molgenis-logging-kibana"
#                servicePort: 5601
