elasticsearch:
  image: "docker.elastic.co/elasticsearch/elasticsearch-oss"
  # Enabling this will publically expose your Elasticsearch instance.
  # Only enable this if you have security enabled on your cluster
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/whitelist-source-range: 195.169.22.0/23
    paths: /
    hosts:
      - logging.edge.molgenis.org
  extraEnvs:
    - name: ELASTIC_PASSWORD
      valueFrom:
        secretKeyRef:
          name: Elastic password
          key: logging.password
    - name: ELASTIC_USERNAME
      valueFrom:
        secretKeyRef:
          name: Elastic user
          key: logging.user

    extraEnvs:
      - name: ELASTIC_PASSWORD
        valueFrom:
          secretKeyRef:
            name: "elastic-credentials"
            key: password
      - name: ELASTIC_USERNAME
        valueFrom:
          secretKeyRef:
            name: "elastic-credentials"
            key: username
    authentication:
      username: xxxx
      password: xxxx
    
kibana:
  image: "docker.elastic.co/kibana/kibana-oss"
  ingress:
    enabled: true
    annotations: 
      nginx.ingress.kubernetes.io/auth-type: basic
      nginx.ingress.kubernetes.io/auth-secret: kibana-credentials
      nginx.ingress.kubernetes.io/auth-realm: "Authentication Required - kibana"
    path: /
    hosts:
      - kibana.edge.molgenis.org
  extraEnvs:
    - name: 'ELASTICSEARCH_USERNAME'
      valueFrom:
        secretKeyRef:
          name: Elastic user
          key: logging.user
    - name: 'ELASTICSEARCH_PASSWORD'
      valueFrom:
        secretKeyRef:
          name: Elastic password
          key: logging.password
  authentication:
    username: xxxx
    password: xxxx
