elasticsearch:
  image: "docker.elastic.co/elasticsearch/elasticsearch-oss"
  # Enabling this will publically expose your Elasticsearch instance.
  # Only enable this if you have security enabled on your cluster
  ingress:
    enabled: true
    annotations:
      ingress.kubernetes.io/whitelist-source-range: 195.169.22.0/23
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    paths: /
    hosts: 
      - logging.edge.molgenis.org
  extraEnvs:
    - name: ELASTIC_PASSWORD
      valueFrom:
        secretKeyRef:
          name: "Elastic password"
          key: logging.password
    - name: ELASTIC_USERNAME
      valueFrom:
        secretKeyRef:
          name: "Elastic user"
          key: logging.user

kibana:
  elasticsearchURL: "logging.edge.molgenis.org:443"
  image: "docker.elastic.co/kibana/kibana-oss"
  ingress:
    enabled: true
    annotations: {}
    path: /
    hosts:
      - kibana.edge.molgenis.org
  extraEnvs:
    - name: 'ELASTICSEARCH_USERNAME'
      valueFrom:
        secretKeyRef:
          name: "Elastic user"
          key: logging.user
    - name: 'ELASTICSEARCH_PASSWORD'
      valueFrom:
        secretKeyRef:
          name: "Elastic password"
          key: logging.password
