apiVersion: v1
kind: Secret
metadata:
  name: {{ include "molgenis-auth.fullname" . }}-secretoauth
  labels:
{{ include "molgenis-auth.labels" . | indent 4 }}
type: Opaque
data:
  client_id: {{ $.Values.oauth.client_id | b64enc | quote }}
  client_secret: {{ $.Values.oauth.client_secret | b64enc | quote }}