apiVersion: v1
kind: Secret
metadata:
  name: {{ include "molgenis-auth.fullname" . }}-secretserver
  labels:
{{ include "molgenis-auth.labels" . | indent 4 }}
type: Opaque
data:
  api_token: {{ $.Values.server.api_token | b64enc | quote }}
  app_session_secret: {{ uuidv4 | b64enc | quote }}