apiVersion: "etcd.database.coreos.com/v1beta2"
kind: "EtcdBackup"
metadata:
  generateName: vault-backup-
spec:
  clientTLSSecret: vault-etcd-client-tls
  etcdEndpoints:
      - https://vault-etcd-client:2379
  storageType: ABS
  abs:
    absSecret: abs
    path: vault/<specify name>
