dependencies:
  - name: prometheus
    version: ^7.1.3
    repository: https://kubernetes-charts.storage.googleapis.com/
  - name: grafana
    version: ^1.18.0
    repository: https://kubernetes-charts.storage.googleapis.com/
