apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "nexus.fullname" . }}
  labels:
    app: {{ template "nexus.name" . }}
    chart: {{ template "nexus.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "nexus.name" . }}
      release: {{ .Release.Name }}
  strategy:
    type: {{ .Values.nexus.strategy.type }}
  template:
    metadata:
      labels:
        app: {{ template "nexus.name" . }}
        release: {{ .Release.Name }}
    spec:
      restartPolicy: {{ .Values.nexus.restartPolicy }}
      # {{- if .Values.persistence.enabled }}
      # initContainers:
      # - name: nexus-nfs
      #   image: busybox
      #   command: ["sh", "-c", "chown -R 200:200 /nexus-data"]
      #   volumeMounts:
      #   - name: pv-molgenis-nexus
      #     mountPath: "/nexus-data"
      # {{- end}}
      containers:
      - name: {{ .Values.nexus.name }}
        image: "{{ .Values.nexus.image.repository }}/{{ .Values.nexus.image.name }}:{{ .Values.nexus.image.tag }}"
        imagePullPolicy: {{ .Values.nexus.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.nexus.port.ui }}
        - containerPort: {{ .Values.nexus.port.docker }}
        {{- if .Values.persistence.enabled }}
        volumeMounts:
        - name: pv-molgenis-nexus
          mountPath: /nexus-data
        {{- end }}
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.nexus.port.ui }}
          initialDelaySeconds: 60
          periodSeconds: 30
          failureThreshold: 15
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.nexus.port.ui }}
          initialDelaySeconds: 100
          periodSeconds: 30
          failureThreshold: 15
          successThreshold: 1
      volumes:
        - name: pv-molgenis-nexus
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "nexus.fullname" .) }}
          {{- else }}
          emptyDir: {}
          {{- end -}}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}