# Default values for opencpu.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

environment: production

service:
  name: opencpu
  type: ClusterIP
  port: 8004

opencpu:
  name: opencpu
  strategy:
    type: Recreate
  restartPolicy: Always
  image:
    repository: registry.hub.docker.com
    name: molgenis/opencpu
    tag: latest
    pullPolicy: Always
  resources:
    limits:
      cpu: 4
      memory: 3Gi
    requests:
      cpu: 200m
      memory: 1500Mi

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 0
  path: /
  hosts:
    - name: opencpu.molgenis.org
  firewall:
    enabled: true
    rules:
      - 127.0.0.1/24
      - 127.0.1.1/24
  tls: []

nodeSelector: {}

tolerations: []

affinity: {}
