apiVersion: v1
appVersion: 3.15.2-01
description: Nexus stack for MOLGENIS
name: molgenis-nexus
version: 0.5.1
sources:
- https://github.com/molgenis/molgenis-ops-helm.git
icon: https://raw.githubusercontent.com/molgenis/molgenis-ops-helm/master/charts/molgenis-nexus/catalogIcon-molgenis-nexus.png
home: https://www.sonatype.com/nexus-repository-oss
maintainers:
- name: sidohaakma
- name: fdlk
