apiVersion: v1
kind: Secret
metadata:
  name: elastic-credentials
  labels:
    app: molgenis-logging
    chart: Chart.yml
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  logging.username: {{ .Values.kibana.elastic.username | quote }}
  logging.password: {{ .Values.kibana.elastic.password | b64enc | quote }}
