# Default values for molgenis.

replicaCount: 1

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
  # This will be used again when external domains need be attached to the instance
  # hosts:
  # - name: test
  firewall:
    enabled: true
    kind: "umcg"
  path: /
  tls: []

molgenis:
  advanced: false
  type:
    kind: medium
    small:
      javaOpts:
        maxHeapSpace: "2g"
      resources:
        limits:
          cpu: 2
          memory: 2Gi
        requests:
          cpu: 200m
          memory: 2Gi
      persistence:
        size: 5Gi
    medium:
      javaOpts:
        maxHeapSpace: "3g"
      resources:
        limits:
          cpu: 3
          memory: 3Gi
        requests:
          cpu: 200m
          memory: 3Gi
      persistence:
        size: 10Gi
    large:
      javaOpts:
        maxHeapSpace: "4g"
      resources:
        limits:
          cpu: 4
          memory: 4Gi
        requests:
          cpu: 200m
          memory: 4Gi
      persistence:
        size: 30Gi
  environment: test
  image:
    repository: registry.hub.docker.com
    name: molgenis/molgenis-app
    tag: stable
    pullPolicy: Always
  adminPassword:
  persistence:
    claim: molgenis-nfs-claim
  services:
    opencpu:
      host: localhost
    elasticsearch:
      transportAddresses: localhost:9300
      clusterName: molgenis
    postgres:
      host: localhost
      scheme: molgenis
      user: molgenis
      password: molgenis

elasticsearch:
  type:
    small:
      javaOpts: "-Xms512m -Xmx512m"
      resources:
        limits:
          cpu: 2
          memory: 1500Mi
        requests:
          cpu: 100m
          memory: 1Gi
      persistence:
        size: 5Gi
    medium:
      javaOpts: "-Xms1g -Xmx1g"
      resources:
        limits:
          cpu: 2
          memory: 3Gi
        requests:
          cpu: 100m
          memory: 3Gi
      persistence:
        size: 10Gi
    large:
      javaOpts: "-Xms2g -Xmx2g"
      resources:
        limits:
          cpu: 2
          memory: 5Gi
        requests:
          cpu: 100m
          memory: 5Gi
      persistence:
        size: 20Gi
  image:
    repository: docker.elastic.co/elasticsearch/elasticsearch
    tag: 5.5.3
    pullPolicy: IfNotPresent
  clusterName: molgenis
  persistence:
    claim: elasticsearch-nfs-claim

postgres:
  enabled: true
  ## Specify runtime config parameters as a dict, using camelCase
  ## ref: https://www.postgresql.org/docs/current/static/runtime-config.html
  config:
    maxLocksPerTransaction: 1024
  type:
    small:
      resources:
        limits:
          cpu: 1
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 512Mi
      persistence:
        size: 5Gi
    medium:
      resources:
        limits:
          cpu: 2
          memory: 2Gi
        requests:
          cpu: 100m
          memory: 2Gi
      persistence:
        size: 10Gi
    large:
      resources:
        limits:
          cpu: 4
          memory: 4Gi
        requests:
          cpu: 100m
          memory: 4Gi
      persistence:
        size: 15Gi
  image:
    repository: postgres
    tag: 9.6-alpine
    pullPolicy: IfNotPresent

  persistence:
    claim: postgres-nfs-claim

persistence:
  enabled: true
  retain: false

nodeSelector: {
  deployPod: "true"
}

tolerations: []

affinity: {}
