# Default values for molgenis.

replicaCount: 1

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 0
  path: /
  tls: []

molgenis:
  advanced: false
  type:
    kind: medium
    small:
      javaOpts:
        maxHeapSpace: "2g"
      resources:
        limits:
          cpu: 2
          memory: 2Gi
        requests:
          cpu: 200m
          memory: 2Gi
      persistence:
        size: 5Gi
    medium:
      javaOpts:
        maxHeapSpace: "3g"
      resources:
        limits:
          cpu: 3
          memory: 3Gi
        requests:
          cpu: 200m
          memory: 3Gi
      persistence:
        size: 10Gi
    large:
      javaOpts:
        maxHeapSpace: "4g"
      resources:
        limits:
          cpu: 4
          memory: 4Gi
        requests:
          cpu: 200m
          memory: 4Gi
      persistence:
        size: 30Gi
  environment: test
  # Sentry config. The format is https://{public key}@sentry.molgenis.org/{project id}
  sentry:
    dsn: xxxx
  image:
    repository: registry.hub.docker.com
    name: molgenis/molgenis-app
    tag: stable
    pullPolicy: Always
  adminPassword:
  persistence:
    claim: molgenis-nfs-claim
  services:
    opencpu:
      host: localhost
    elasticsearch:
      clusterName: molgenis
    postgres:
      host: localhost
      scheme: molgenis
      user: molgenis
      password: molgenis

elastic:
  small:
    javaOpts: &elasticSmallJavaOpts "-Xms2g -Xmx2g"
    resources:
      limits:
        cpu: &elasticSmallResourceLimitsCpu 2
        memory: &elasticSmallResourceLimitsMemory 2Gi
      requests:
        cpu: &elasticSmallResourceRequestCpu 200m
        memory: &elasticSmallResourceRequestMemory 2Gi
    persistence:
      size: 5Gi
  medium:
    javaOpts: "-Xms1g -Xmx1g"
    resources:
      limits:
        cpu: 3
        memory: 3Gi
      requests:
        cpu: 200m
        memory: 3Gi
    persistence:
      size: 10Gi
  large:
    javaOpts: "-Xms1g -Xmx1g"
    resources:
      limits:
        cpu: 4
        memory: 4Gi
      requests:
        cpu: 200m
        memory: 4Gi
    persistence:
      size: 30Gi

molgenis-elasticsearch:
  persistence:
    enabled: true
  master:
    javaOpts: *elasticSmallJavaOpts
    resources:
      limits:
        cpu: *elasticSmallResourceLimitsCpu
        memory: *elasticSmallResourceLimitsMemory
      requests:
        cpu: *elasticSmallResourceRequestCpu
        memory: *elasticSmallResourceRequestMemory

postgres:
  enabled: true
  ## Specify runtime config parameters as a dict, using camelCase
  ## ref: https://www.postgresql.org/docs/current/static/runtime-config.html
  config:
    maxLocksPerTransaction: 1024
  type:
    small:
      resources:
        limits:
          cpu: 1
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 512Mi
      persistence:
        size: 5Gi
    medium:
      resources:
        limits:
          cpu: 2
          memory: 2Gi
        requests:
          cpu: 100m
          memory: 2Gi
      persistence:
        size: 10Gi
    large:
      resources:
        limits:
          cpu: 4
          memory: 4Gi
        requests:
          cpu: 100m
          memory: 4Gi
      persistence:
        size: 15Gi
  image:
    repository: postgres
    tag: 9.6-alpine
    pullPolicy: IfNotPresent

  persistence:
    claim: postgres-nfs-claim

persistence:
  enabled: true
  retain: false

nodeSelector: {
  deployPod: "true"
}

tolerations: []

affinity: {}
