# Default values for molgenis.

replicaCount: 1

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 0
  path: /
  tls: []

molgenis:
  advanced: false
  type:
    kind: medium
    small:
      javaOpts:
        maxHeapSpace: "2g"
      resources:
        limits:
          cpu: 2
          memory: 2Gi
        requests:
          cpu: 200m
          memory: 2Gi
      persistence:
        size: 5Gi
    medium:
      javaOpts:
        maxHeapSpace: "3g"
      resources:
        limits:
          cpu: 3
          memory: 3Gi
        requests:
          cpu: 200m
          memory: 3Gi
      persistence:
        size: 10Gi
    large:
      javaOpts:
        maxHeapSpace: "4g"
      resources:
        limits:
          cpu: 4
          memory: 4Gi
        requests:
          cpu: 200m
          memory: 4Gi
      persistence:
        size: 30Gi
  environment: test
  # Sentry config. The format is https://{public key}@sentry.molgenis.org/{project id}
  sentry:
    dsn: xxxx
  python:
    executable: "/usr/bin/python3"
  image:
    repository: registry.hub.docker.com
    name: molgenis/molgenis-app
    tag: stable
    pullPolicy: Always
  admin:
    password:
    email: no-reply@molgenis.org
  anonymous:
    email: anonymous@molgenis.org
  persistence:
    claim: pvc-molgenis
  services:
    opencpu:
      host: localhost
  mail:
    host: smtp.rug.nl
    username:
    password:

molgenis-elasticsearch:
  persistence:
    enabled: true
  master:
    clusterName: molgenis
    javaOpts: "-Xms1g -Xmx1g"
    resources:
      limits:
        cpu: 2
        memory: 2Gi
      requests:
        cpu: 200m
        memory: 2Gi
    persistence:
      size: 10Gi

postgresql:
  persistence:
    enabled: true
    size: 10Gi
  image:
    tag: 9.6.11
  ## Specify runtime config parameters as a dict, using camelCase
  ## ref: https://www.postgresql.org/docs/current/static/runtime-config.html
  configuration:
    maxLocksPerTransaction: 1024
  postgresqlUsername: molgenis
  postgresqlPassword: molgenis
  postgresqlDatabase: molgenis


persistence:
  enabled: true
  retain: false

nodeSelector: {
  deployPod: "true"
}

tolerations: []

affinity: {}
